### ISSUE TITLE
Reunion fail to load

### ISSUE THREAD

**Issue by jamesjamesbond1999** [rehlds/reunion#5]
Reunion fail to load, ubuntu 20 x64

![reunion fail to load](https://github.com/user-attachments/assets/578d0fc4-7afe-4f0d-93da-070a17416106)

metamod-1.21.1-am
reunion_0_1_0_92d

a follow this steps and fail to load

Go to <gamedir>/addons/ and make new directory named reunion
<gamedir> - its a game directory; cstrike for Counter-Strike, valve for Half-Life, etc
Go to <gamedir>/addons/ and make new directory named reunion
<gamedir> - its a game directory; cstrike for Counter-Strike, valve for Half-Life, etc
Copy reunion_mm.dll or reunion_mm_i386.so to <gamedir>/addons/reunion/
Go to metamod installation directory (usually its <gamedir>/addons/metamod/) and edit plugins.ini:
add this line for windows
win32 addons\reunion\reunion_mm.dll
or this for linux
linux addons/reunion/reunion_mm_i386.so
at the beginning of the file
Copy reunion.cfg to server root or gamedir.

**Comment by jamesjamesbond1999** [comment]
thanks, reunion still fail start new log

[REUNION]: Failed to locate REHLDS API
L 11/06/2024 - 18:41:27: [REUNION]: Failed to locate REHLDS API
L 11/06/2024 - 18:41:27: [META] ERROR: dll: Failed attach plugin 'Reunion': Error from Meta_Attach(): 0
L 11/06/2024 - 18:41:27: [META] ERROR: dll: Failed to attach plugin 'Reunion'
L 11/06/2024 - 18:41:27: [META] ERROR: dll: Failed to load plugin 'reunion_mm_i386.so'
L 11/06/2024 - 18:41:27: [META] dll: Finished loading 1 plugins

**Comment by wopox1337** [comment]
> ```c++
> [REUNION]: Failed to locate REHLDS API
> ```

give answer from `version` (in console) please

**Comment by jamesjamesbond1999** [comment]
AMX Mod X version 1.9.0.5294 Copyright (c) 2004-2015 AMX Mod X Development Team 
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under 
   certain conditions; type 'amxx gpl' for details.
  
L 11/06/2024 - 18:41:27: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.9.0.5294 Jun  3 2020, AMX Mod X Dev Team
[REUNION]: Failed to locate retrieve rehlds api interface from REHLDS engine module, return code is 1
L 11/06/2024 - 18:41:27: [REUNION]: Failed to locate retrieve rehlds api interface from REHLDS engine module, return code is 1
[REUNION]: Failed to locate REHLDS API
L 11/06/2024 - 18:41:27: [REUNION]: Failed to locate REHLDS API
L 11/06/2024 - 18:41:27: [META] ERROR: dll: Failed attach plugin 'Reunion': Error from Meta_Attach(): 0
L 11/06/2024 - 18:41:27: [META] ERROR: dll: Failed to attach plugin 'Reunion'
L 11/06/2024 - 18:41:27: [META] ERROR: dll: Failed to load plugin 'reunion_mm_i386.so'
L 11/06/2024 - 18:41:27: [META] dll: Finished loading 1 plugins
L 11/06/2024 - 18:41:27: Log file closed


    description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.9.0.5  ini  Start ANY  
 [ 2] Reunion               fail load  reunion_mm_i386.  v0.2.0.1  ini  Start Never
 [ 3] Ham Sandwich    RUN   -    hamsandwich_amxx  v1.9.0.5  pl1  ANY   ANY  
 [ 4] CSX                      RUN   -    csx_amxx_i386.so  v1.9.0.5  pl1  ANY   ANY  
 [ 5] FakeMeta             RUN   -    fakemeta_amxx_i3  v1.9.0.5  pl1  ANY   ANY  
 [ 6] MySQL                 RUN   -    mysql_amxx_i386.  v1.9.0.5  pl1  ANY   ANY

**Comment by wopox1337** [comment]
> AMX Mod X version 1.9.0.5294

You install the Metamod plugin **ReUnion**, it requires the ReHLDS version of the engine (its API). We need to know what version of HLDS (console command `version`) you have, and we are not interested in another Metamod plugin (AMXModX) at the moment.

**Comment by jamesjamesbond1999** [comment]
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 01:34:04 Oct  8 2024 (10211)

**Comment by wopox1337** [comment]
> need to install [ReHLDS](https://github.com/rehlds/rehlds) (as said [requirement section](https://github.com/rehlds/reunion?tab=readme-ov-file#environment-requirement))

**Comment by jamesjamesbond1999** [comment]
i  installed ReHLDS on top of it.

chmod +x hlds_linux hlds_run

run server and server crash

**Comment by wopox1337** [comment]
> Exe build: 01:34:04 Oct  8 2024 (10211)

It's not ReHLDS.

**Comment by jamesjamesbond1999** [comment]
root@ubuntu-teste:/home/cs# ./hlds_run -console -game cstrike +maxplayers 12 +map de_dust2 +log on -debug
Enabling debug mode
./hlds_run: 1: gdb: not found
Please install gdb first.
goto http://www.gnu.org/software/gdb/ 
Auto-restarting the server on crash
Error: /home/cs/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
cat: hlds.85882.pid: No such file or directory
                                              email debug.log to linux@valvesoftware.com
                                                                                        Wed 06 Nov 2024 07:19:15 PM UTC: Server restart in 10 seconds
                    Error: /home/cs/engine_i486.so: undefined symbol: SteamGameServer
                                                                                     Unable to load engine, image is corrupt.

**Comment by stamepicmorg** [comment]
> i installed ReHLDS on top of it.

hello. describe please, how did you installed rehlds?

**Comment by stamepicmorg** [comment]
> i donwload last release from https://github.com/rehlds/rehlds/releases/tag/3.13.0.788
> 
> extract file, i copy all content folder linux32 for server

ok, thank you. 

how did you installed hlds before? via steamcmd?

did you installed latest version or installed with legacy banch?

current version of rehlds and plugins not compatible with fresh 25'th update of hlds and needs old release version.

**Comment by jamesjamesbond1999** [comment]
i installed server cs 1.6 wiht steamcmd terminal ubuntu

latest version

app_update 90

**Comment by stamepicmorg** [comment]
>  i installed server cs 1.6 with steamcmd terminal ubuntu 20
> 
> latest version
> 
> app_update 90
> 
> how install with legacy banch 

app_update 90 -beta steam_legacy validate

**Comment by jamesjamesbond1999** [comment]
thanks bro

**Comment by stamepicmorg** [comment]
> thanks bro

welcome

but try to clean install instead of downgrading from "25th" to "legacy" to prevent unexpected errors.

**Comment by jamesjamesbond1999** [comment]
i go remove all and try =D

**Comment by jamesjamesbond1999** [comment]
Reunion and REhlds not work with updated server app_update 90

only work fine with legacy, print screen

![fix reunion](https://github.com/user-attachments/assets/49c59d67-49ee-4b45-b914-28c07643bfb0)

many thanks for all brothers

**Comment by jamesjamesbond1999** [comment]
any plugin or comand for server appear on internet list
my server not appear =(
